---
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

group: dev

install:
  - pip install .
  - pip install -r tests/requirements.txt

env:
  - PYTHONPATH=.

# command to run tests
script:
  - python -Werror tests/smoke_test.py
  - python -m unittest discover tests
  - echo test
